function compile_indirect(flags, common_scs)

scs_root_dir = get_scs_rootdir();
scs_matlab_dir = fullfile(scs_root_dir, 'matlab/');
linsys_indirect_dir = fullfile(scs_root_dir, 'linsys/indirect/');
include_dir = fullfile(scs_root_dir, 'include/');

% compile indirect
if (flags.COMPILE_WITH_OPENMP)
    cmd = sprintf(['mex -Ofast %s %s %s %s COMPFLAGS="/openmp \\$COMPFLAGS" ' ...
        'CFLAGS="\\$CFLAGS -fopenmp" ' linsys_indirect_dir 'private.c '  ...
        '%s -I' scs_root_dir ' -I' include_dir ' %s %s %s -output scs_indirect'], ...
        flags.arr, flags.LCFLAG, common_scs, flags.INCS, flags.link, ...
        flags.LOCS, flags.BLASLIB, flags.INT);
else
    cmd = sprintf(['mex -O %s %s %s %s ' linsys_indirect_dir 'private.c %s ' ...
        '-I' scs_root_dir ' -I' include_dir ' -I' scs_root_dir 'linsys %s %s %s' ...
        ' -output ' scs_matlab_dir 'scs_indirect'],  ...
        flags.arr, flags.LCFLAG, common_scs, flags.INCS, flags.link, ...
        flags.LOCS, flags.BLASLIB, flags.INT);
end
eval(cmd);
