function set_pars(o, tol)


cvx_solver_settings('alpha', o.alpha, ...
    'beta', o.beta,...
    'c1', o.c1, ...
    'c_bl', o.c_bl, ...
    'cg_rate', o.cg_rate, ...
    'direction', o.direction, ...
    'do_super_scs',o.do_super_scs, ...
    'eps', tol,...
    'k0', o.k0, ...
    'k1', o.k1, ...
    'k2', o.k2, ...
    'ls',  o.ls, ...
    'memory', o.memory, ...
    'normalize', o.normalize, ...
    'rho_x', o.rho_x, ...
    'scale', o.scale, ...
    'sigma', o.sigma,...
    'sse', o.sse,...
    'thetabar', o.thetabar,...
    'verbose', o.verbose, ...
    'do_record_progress', o.do_record_progress,...
    'warm_start', o.warm_start)

if isfield(o, 'dumpfile'),
    cvx_solver_settings('dumpfile', o.dumpfile);
end

if isfield(o, 'use_indirect') && o.use_indirect,
    cvx_solver_settings('use_indirect', o.use_indirect);
end