function set_pars(solver_ops)


cvx_solver_settings(...
    'alpha', solver_ops.alpha, ...
    'beta', solver_ops.beta,...
    'c1', solver_ops.c1, ...
    'c_bl', solver_ops.c_bl, ...
    'cg_rate', solver_ops.cg_rate, ...
    'direction', solver_ops.direction, ...
    'do_super_scs',solver_ops.do_super_scs, ...
    'eps', solver_ops.tolerance,...
    'k0', solver_ops.k0, ...
    'k1', solver_ops.k1, ...
    'k2', solver_ops.k2, ...
    'ls',  solver_ops.ls, ...
    'memory', solver_ops.memory, ...
    'normalize', solver_ops.normalize, ...
    'rho_x', solver_ops.rho_x, ...
    'scale', solver_ops.scale, ...
    'sigma', solver_ops.sigma,...
    'sse', solver_ops.sse,...
    'thetabar', solver_ops.thetabar,...
    'verbose', solver_ops.verbose, ...
    'do_record_progress', solver_ops.do_record_progress,...
    'warm_start', solver_ops.warm_start,...
    'max_iters', solver_ops.max_iters)

if isfield(solver_ops, 'dumpfile'),
    cvx_solver_settings('dumpfile', solver_ops.dumpfile);
end

if isfield(solver_ops, 'use_indirect'),
    cvx_solver_settings('use_indirect', solver_ops.use_indirect);
end